name: Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build caddy
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        go: [~1.22.1]
    uses: ./.github/workflows/build.yml
    with:
      build_from: "@${{ github.ref_name}}"
      goos: ${{ matrix.goos }}
      goarch: ${{ matrix.goarch }}
      go: ${{ matrix.go }}

  release:
    name: Create release notes
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: caddy-*
          merge-multiple: true

      - name: Create release notes
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: "caddy-*"
          prerelease: true
